name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo check --verbose
    - name: Clippy
      run: cargo clippy --verbose
    - name: Format check
      run: cargo fmt --check
