name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust (windows-gnu)
      run: rustup toolchain install stable-x86_64-pc-windows-gnu && rustup default stable-x86_64-pc-windows-gnu
    - name: Check
      run: cargo check --verbose
    - name: Clippy
      run: cargo clippy --verbose
    - name: Format check
      run: cargo fmt --check
